package com.leo.entity;

import java.util.Date;

public class SysUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_base.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_base.LOGIN_NAME
     *
     * @mbggenerated
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_base.PASSWORD
     *
     * @mbggenerated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_base.NICK_NAME
     *
     * @mbggenerated
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_base.PHOTO
     *
     * @mbggenerated
     */
    private String photo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_base.MOBILE
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_base.EMAIL
     *
     * @mbggenerated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_base.QQ
     *
     * @mbggenerated
     */
    private String qq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_base.WECHAT
     *
     * @mbggenerated
     */
    private String wechat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_base.USER_TYPE
     *
     * @mbggenerated
     */
    private String userType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_base.VIP_LEVEL
     *
     * @mbggenerated
     */
    private String vipLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_base.USER_LEVEL
     *
     * @mbggenerated
     */
    private String userLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_base.IDCARD
     *
     * @mbggenerated
     */
    private String idcard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_base.IDCARD_LAST
     *
     * @mbggenerated
     */
    private String idcardLast;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_base.REAL_NAME
     *
     * @mbggenerated
     */
    private String realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_base.VIP_END_DATE
     *
     * @mbggenerated
     */
    private Date vipEndDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_base.MOBILE_STATUS
     *
     * @mbggenerated
     */
    private String mobileStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_base.EMAIL_STATUS
     *
     * @mbggenerated
     */
    private String emailStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_base.USER_STATUS
     *
     * @mbggenerated
     */
    private String userStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_base.CREATE_DATE
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_base.ID
     *
     * @return the value of sys_user_base.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_base.ID
     *
     * @param id the value for sys_user_base.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_base.LOGIN_NAME
     *
     * @return the value of sys_user_base.LOGIN_NAME
     *
     * @mbggenerated
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_base.LOGIN_NAME
     *
     * @param loginName the value for sys_user_base.LOGIN_NAME
     *
     * @mbggenerated
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_base.PASSWORD
     *
     * @return the value of sys_user_base.PASSWORD
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_base.PASSWORD
     *
     * @param password the value for sys_user_base.PASSWORD
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_base.NICK_NAME
     *
     * @return the value of sys_user_base.NICK_NAME
     *
     * @mbggenerated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_base.NICK_NAME
     *
     * @param nickName the value for sys_user_base.NICK_NAME
     *
     * @mbggenerated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_base.PHOTO
     *
     * @return the value of sys_user_base.PHOTO
     *
     * @mbggenerated
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_base.PHOTO
     *
     * @param photo the value for sys_user_base.PHOTO
     *
     * @mbggenerated
     */
    public void setPhoto(String photo) {
        this.photo = photo == null ? null : photo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_base.MOBILE
     *
     * @return the value of sys_user_base.MOBILE
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_base.MOBILE
     *
     * @param mobile the value for sys_user_base.MOBILE
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_base.EMAIL
     *
     * @return the value of sys_user_base.EMAIL
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_base.EMAIL
     *
     * @param email the value for sys_user_base.EMAIL
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_base.QQ
     *
     * @return the value of sys_user_base.QQ
     *
     * @mbggenerated
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_base.QQ
     *
     * @param qq the value for sys_user_base.QQ
     *
     * @mbggenerated
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_base.WECHAT
     *
     * @return the value of sys_user_base.WECHAT
     *
     * @mbggenerated
     */
    public String getWechat() {
        return wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_base.WECHAT
     *
     * @param wechat the value for sys_user_base.WECHAT
     *
     * @mbggenerated
     */
    public void setWechat(String wechat) {
        this.wechat = wechat == null ? null : wechat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_base.USER_TYPE
     *
     * @return the value of sys_user_base.USER_TYPE
     *
     * @mbggenerated
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_base.USER_TYPE
     *
     * @param userType the value for sys_user_base.USER_TYPE
     *
     * @mbggenerated
     */
    public void setUserType(String userType) {
        this.userType = userType == null ? null : userType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_base.VIP_LEVEL
     *
     * @return the value of sys_user_base.VIP_LEVEL
     *
     * @mbggenerated
     */
    public String getVipLevel() {
        return vipLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_base.VIP_LEVEL
     *
     * @param vipLevel the value for sys_user_base.VIP_LEVEL
     *
     * @mbggenerated
     */
    public void setVipLevel(String vipLevel) {
        this.vipLevel = vipLevel == null ? null : vipLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_base.USER_LEVEL
     *
     * @return the value of sys_user_base.USER_LEVEL
     *
     * @mbggenerated
     */
    public String getUserLevel() {
        return userLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_base.USER_LEVEL
     *
     * @param userLevel the value for sys_user_base.USER_LEVEL
     *
     * @mbggenerated
     */
    public void setUserLevel(String userLevel) {
        this.userLevel = userLevel == null ? null : userLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_base.IDCARD
     *
     * @return the value of sys_user_base.IDCARD
     *
     * @mbggenerated
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_base.IDCARD
     *
     * @param idcard the value for sys_user_base.IDCARD
     *
     * @mbggenerated
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard == null ? null : idcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_base.IDCARD_LAST
     *
     * @return the value of sys_user_base.IDCARD_LAST
     *
     * @mbggenerated
     */
    public String getIdcardLast() {
        return idcardLast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_base.IDCARD_LAST
     *
     * @param idcardLast the value for sys_user_base.IDCARD_LAST
     *
     * @mbggenerated
     */
    public void setIdcardLast(String idcardLast) {
        this.idcardLast = idcardLast == null ? null : idcardLast.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_base.REAL_NAME
     *
     * @return the value of sys_user_base.REAL_NAME
     *
     * @mbggenerated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_base.REAL_NAME
     *
     * @param realName the value for sys_user_base.REAL_NAME
     *
     * @mbggenerated
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_base.VIP_END_DATE
     *
     * @return the value of sys_user_base.VIP_END_DATE
     *
     * @mbggenerated
     */
    public Date getVipEndDate() {
        return vipEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_base.VIP_END_DATE
     *
     * @param vipEndDate the value for sys_user_base.VIP_END_DATE
     *
     * @mbggenerated
     */
    public void setVipEndDate(Date vipEndDate) {
        this.vipEndDate = vipEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_base.MOBILE_STATUS
     *
     * @return the value of sys_user_base.MOBILE_STATUS
     *
     * @mbggenerated
     */
    public String getMobileStatus() {
        return mobileStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_base.MOBILE_STATUS
     *
     * @param mobileStatus the value for sys_user_base.MOBILE_STATUS
     *
     * @mbggenerated
     */
    public void setMobileStatus(String mobileStatus) {
        this.mobileStatus = mobileStatus == null ? null : mobileStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_base.EMAIL_STATUS
     *
     * @return the value of sys_user_base.EMAIL_STATUS
     *
     * @mbggenerated
     */
    public String getEmailStatus() {
        return emailStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_base.EMAIL_STATUS
     *
     * @param emailStatus the value for sys_user_base.EMAIL_STATUS
     *
     * @mbggenerated
     */
    public void setEmailStatus(String emailStatus) {
        this.emailStatus = emailStatus == null ? null : emailStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_base.USER_STATUS
     *
     * @return the value of sys_user_base.USER_STATUS
     *
     * @mbggenerated
     */
    public String getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_base.USER_STATUS
     *
     * @param userStatus the value for sys_user_base.USER_STATUS
     *
     * @mbggenerated
     */
    public void setUserStatus(String userStatus) {
        this.userStatus = userStatus == null ? null : userStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_base.CREATE_DATE
     *
     * @return the value of sys_user_base.CREATE_DATE
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_base.CREATE_DATE
     *
     * @param createDate the value for sys_user_base.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}